export const types = Object.freeze({
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',
    FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    FILL_POSTS: 'FILL_POSTS',
    ADD_POST: 'ADD_POST',
    SET_NEW_POST_DATA: 'SET_NEW_POST_DATA',
});
