export const types = {
    //Async
    FETCH_FEED_POSTS_ASYNC: 'FETCH_FEED_POSTS_ASYNC',
    FETCH_USER_POSTS_ASYNC: 'FETCH_USER_POSTS_ASYNC',
    CREATE_POST_ASYNC:      'CREATE_POST_ASYNC',
    DELETE_POST_ASYNC:      'DELETE_POST_ASYNC',
    LIKE_POST_ASYNC:        'LIKE_POST_ASYNC',
    UNLIKE_POST_ASYNC:      'UNLIKE_POST_ASYNC',
    FETCH_COMMENTS_ASYNC:   'FETCH_COMMENTS_ASYNC',
    CREATE_COMMENT_ASYNC:   'CREATE_COMMENT_ASYNC',

    //Sync
    FILL_POSTS:                   'FILL_POSTS',
    ADD_POST:                     'ADD_POST',
    REMOVE_POST:                  'REMOVE_POST',
    CLEAR_POSTS:                  'CLEAR_POSTS',
    LIKE_POST:                    'LIKE_POST',
    UNLIKE_POST:                  'UNLIKE_POST',
    FILL_COMMENTS:                'FILL_COMMENTS',
    ADD_COMMENT:                  'ADD_COMMENT',
    SET_POSTS_FETCHING_STATE:     'SET_POSTS_FETCHING_STATE',
    DISABLE_POSTS_FETCHING_STATE: 'DISABLE_POSTS_FETCHING_STATE',
};
