export const types = {
    //Async
    FETCH_USER_ASYNC:          'FETCH_USER_ASYNC',
    FETCH_POPULAR_USERS_ASYNC: 'FETCH_POPULAR_USERS_ASYNC',

    //Sync
    FILL_USER:                    'FILL_USER',
    CLEAR_USER:                   'CLEAR_USER',
    FILL_POPULAR_USERS:           'FILL_POPULAR_USERS',
    SET_USERS_FETCHING_STATE:     'SET_USERS_FETCHING_STATE',
    DISABLE_USERS_FETCHING_STATE: 'DISABLE_USERS_FETCHING_STATE',
};
