export const types = {
    //Async
    FILL_PROFILE_ASYNC:         'FILL_PROFILE_ASYNC',
    UPDATE_PROFILE_ASYNC:       'UPDATE_PROFILE_ASYNC',
    UPDATE_PROFILE_IMAGE_ASYNC: 'UPDATE_PROFILE_IMAGE_ASYNC',

    //Sync
    FILL_PROFILE:  'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
};
