export const types = Object.freeze({
  //Async
  AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',
  INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  LOGOUT_ASYNC: 'LOGOUT_ASYNC',

  //Sync
  AUTHENTICATE: 'AUTHENTICATE',
  INITIALIZE: 'INITIALIZE',
  LOGOUT: 'LOGOUT',
});